[install]
linker = "hoisted"
[workspace]
members = [
  "packages/site",
  "packages/test"
]
[test]
root = "./packages/test"
preload = ["./packages/test/site/setupTests.ts", "./packages/test/site/bun-test.d.ts"]
